### ISSUE TITLE
.flac files are blacklisted

### ISSUE THREAD

**Issue by wootguy** [wootguy/resguy#10]
Don't include these, and maybe print a warning or something. Check all the other fmod types while you're at it.

Edit - The following types are supported by FMOD but blacklisted by sven:

.aiff, .flac, .it, .midi, .xm

**Comment by incognico** [comment]
If FMOD does play flac, maybe allow them up to a specific size like 1mb or something?

**Comment by wootguy** [comment]
It does play flac, but the files won't be transferred to clients, so no point in adding them to the .res.

**Comment by wootguy** [comment]
Didn't bother adding a warning for this since it should be fixed in sven eventually.
