### ISSUE TITLE
Resguy keeps running indefinitely parsing the map IO

### ISSUE THREAD

**Issue by lampshady** [wootguy/resguy#2]
This is a xpost from the svencoop forum but I thought it may add visibilty:

I found a bug with resguy and it occurs in RNG's IO map. The program loops indefinitely when parsing IO. It pauses after outputting: 
Generating .res file for maps/io_v1
Failed to normalize path: ..rngionpcio_sentences.txt

Link to map: [IO @ scmapdb](http://scmapdb.com/map:io)

**Comment by wootguy** [comment]
Do you get this with the latest revision? I had the same problem but I thought I fixed it in caffdec3f75d4a4851eebcb83f7510b92dfb1c0f.

**Comment by lampshady** [comment]
Oh I was running v12. Should I clone the current repo and run again?

**Comment by wootguy** [comment]
Yeah. Good to know this happens in v12 though, I thought I introduced the bug recently.

**Comment by lampshady** [comment]
Just did a clone of the current git and it's fixed in trunk. Thanks for the quick response. This might suggest a new stable release, maybe v27 skipped 15 version numbers? Closing bug now.

P.S. I see a lot of sentence errors in output; is that intentional? Separate issue I know just asking.

**Comment by wootguy** [comment]
What kind of sentence errors? I just know IO has an invalid path for the sentence file (as do many other maps).
