### ISSUE TITLE
-icase and script precaching

### ISSUE THREAD

**Issue by incognico** [wootguy/resguy#22]
This is probably only affecting me and how I handle my server files but still I'd like to request something:

I lowercase every file before putting it on Sven and I always use -icase.

Now there is one case where it does not work: Files who are precached in scripts and have uppercase chars in the filename. Currently ignore_script_files is true and I guess they are just ignored. 

What would fix this could be something like:
- Parse precached files in map scripts (I think the code is there already for archives)
- Add to list if at least one uppercase char is in the file or folder name
- Add those to the res file in all lowercase (if the file exists on disk)

Sure its a bit hacky but I think it's the best method to be able to run resguy on all maps and get it right with the all lowercase approach. Otherwise I would have to check and edit all map scripts by hand. Maybe as new option -icasescript or something?

Related to #15

**Comment by wootguy** [comment]
So the script has uppercase letters in the path, which precaches, but fails to transfer to clients because the real path is all lowercase? This might just be that I forgot to do a case-insensitive search for script resources when ignore_script_files is disabled.

**Comment by incognico** [comment]
Not the script itself, the files being precached by the script.

**Comment by wootguy** [comment]
Problem was -extra not including script resources at all. I tried "test.ogg" and "TEST.ogg" in a script and both are found with -icase.
