### ISSUE TITLE
External textures in models not always detected 

### ISSUE THREAD

**Issue by incognico** [wootguy/resguy#23]
I installed http://scmapdb.com/map:sa13 - first the repack and then the remaster on top.

resguy does not add houndeyeT.mdl, actually with -icase houndeyet.mdl (and many more T models) to res file. Not sure how resguy detects external textures, maybe they need to be referenced in the original model and this is not the case? If thats the case maybe add a fallback layer to check for a T model for every .mdl file and just add it if it exists on the filesystem.

**Comment by wootguy** [comment]
Those T models probably aren't used. houndeye.mdl loads in a model viewer without the T model. The original/repacked version has some extra T models in it I guess.

A model uses a T model if numtextures=0 in the [model header](https://github.com/wootguy/resguy/blob/master/src/studio.h#L75) and there's at least one triangle to texture.

**Comment by incognico** [comment]
Oh, so the models were merged in the repack and I still have the old ones client-side.
