### ISSUE TITLE
Misc.

### ISSUE THREAD

**Issue by incognico** [wootguy/resguy#4]
Used latest resguy on those 4 maps: http://scmapdb.com/map:justzombies

One map .cfg has map_script with the .as file extension, resguy complains but it seems Sven allows this, so maybe check if .as is in the script name and if so don't append it.

There are also some other errors, maybe legit maybe not on those 4 maps, can't recall at the moment but you might want to have a look.

Ah, maybe also put a new default content file for 5.13.

**Comment by wootguy** [comment]
Thanks, fixed.

I checked out the other missing file errors and they're all legit except for the "nothing" models in justislave. Those will be ignored since they have no triangles and the game is ok with missing textures in that case.
