### ISSUE TITLE
-icase and folder names

### ISSUE THREAD

**Issue by incognico** [wootguy/resguy#5]
Does -icase only apply to file names and not the folders? If yes I'd like to request that it also applies to all folder names in a path.

```
srcds@k:~/sc5/svencoop_addon$ tools/resguy gf_landworld -icase -extra -missing3
Loading default content...Generating .res file for maps/gf_landworld

Missing file "sprites/Gf_landworld/B-Tele1.spr" referenced in:
        gf_landworld.bsp --> "" (env_sprite)

Missing file "sprites/Gf_landworld/flame2.spr" referenced in:
        gf_landworld.bsp --> "fuego" (env_sprite)

Missing file "sprites/Gf_landworld/smokepuff.spr" referenced in:
        gf_landworld.bsp --> "fuego" (env_sprite)


Wrote 26 entries. 3 files missing. 7 files skipped.

srcds@k:~/sc5/svencoop_addon$ ls sprites/gf_landworld/
b-tele1.spr  e-tele1.spr  flame2.spr  smokepuff.spr
```

**Comment by wootguy** [comment]
-icase applies to folder names too. It shows capitals in the "missing file" error since it doesn't know the actual capitalization of the file.

I tried this map on my Lubuntu VM (ext4 filesystem) and didn't get these errors when I used -icase. Does the same thing happen if you run this in an isolated folder?

Edit: Maybe something is wrong with the permissions of those files (or folders)? resguy checks for existence by trying to open the file in read mode.

**Comment by incognico** [comment]
Permissions are all fine rw/rwx for files/folders, also using ext4.

I just checked the .ent and all resources use Gf_landworld (capital G) in the path names. So it seems to me that it is only a problem with sprites, als the other resources are added just fine.

Again with "resguy gf_landworld -icase -extra -missing3" I notice another weird thing:
sprites/Gf_landworld/e-tele1.spr is added to the .res file (with a capital G besides using -icase)!
while the other 3 sprites in the same folder with the same path and the same permissions appear missing.

First I thought it has to do with folder and filename in the .ent being mixed case (sprites/Gf_landworld/B-Tele1.spr) but smokepuff.spr is written case insensitive the in .ent.

**Comment by wootguy** [comment]
Well I'm stumped. The sprites in my res file don't get a capital G in the folder name unless I rename the folder to have that. No matter how I change the caps (files and folders), I'm getting the right output with no missing files. I'm using the same command as you and I'd guess we have the same version of the map.

If you want you could send me a .tar of your files and I'll see what happens on my end. I don't know what else to try.

**Comment by incognico** [comment]
Weird. I just recloned and recompiled resguy and grabbed the map again from scmapdb to be sure we have the same stuff. The only thing I did after unpacking the map was to rename B-Tele1.spr  to b-tele1.spr and then I ran resguy. It is still the same, see for yourself: https://youtu.be/50j7HzVYwQI

**Comment by wootguy** [comment]
I followed along and set the same permissions and filename, but it went well for me :\

I also did a fresh install of Debian and got the same results: https://youtu.be/5tksaGz0zpk

I think something's wrong with your OS or compiler. No idea what though - I don't use Linux much.

**Comment by incognico** [comment]
Okay. When I do it in a clean folder it works as intended (just did it exactly like you). Afterwards I copied the exact same files from the working folder to my servers svencoop_addon folder and it stops working correctly. On a side not the -log option does not create a file in neither folder.

So there seems to be something in my sc installation which causes that. After testing it seems related to the sprite folder. Maybe im hitting some limit? Including folders theres slightly over 1024 files can't think of anything else. A corrupt file maybe? Heres my sprite folder, just use it together with a clean folder structure (and this landworld map) like you did in the video, you should be able to reproduce it then: http://148.251.69.41:8889/sc5/work/sprites.tar.gz

**Comment by incognico** [comment]
Ah crap, it was because sprites/Gf_landworld/e-tele1.spr also existed in there. Though all files are present in the lowecase folder version.

**Comment by wootguy** [comment]
Yep that was it. The program gave up after searching the Gf_landworld folder.
