### ISSUE TITLE
Parse CustomSpriteDir keyvalue

### ISSUE THREAD

**Issue by R4to0** [wootguy/resguy#7]
It would be great if you could make to parse CustomSpriteDir keyvalue in resguy. This keyvalue is used for setting custom hud sprite dir for weapon_* entities. 

For example, from po_c2a1.bsp:

```
{
"origin" "363 369 288"
"angles" "0 29 0"
"CustomSpriteDir" "poke646"
"classname" "weapon_satchel"
}
```

which points to sprites/poke646/weapon_satchel.txt

Thanks!

**Comment by wootguy** [comment]
Done. I didn't know that existed!
